import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/dist/compiled/@next/font/dist/local";

const helvatica = localFont({
    src: [
        {
            path: './fonts/HelveticaNeueBold.otf',
            weight: '600',
            style: 'normal'
        },
        {
            path: './fonts/HelveticaNeueMedium.otf',
            weight: '400',
            style: 'normal'
        },
        {
            path: './fonts/HelveticaNeueLight.otf',
            weight: '200',
            style: 'normal'
        },
        {
            path: './fonts/HelveticaNeueThin.otf',
            weight: '100',
            style: 'normal'
        }
    ]
})

export const metadata: Metadata = {
  title: "Hello Next JS 🥲",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
